install.packages("tidyverse")
install.packages("BiocManager")
system("echo Y | sudo apt-get install zlib1g-dev")
system("echo Y | sudo apt install libssl-dev")
system("echo Y | sudo apt install libcurl4-openssl-dev")
system("echo Y | sudo apt install libxml2-dev")
system("echo Y | sudo apt-get install libhdf5-dev")
system("echo Y | sudo apt-get install libproj-dev libgdal-dev")
system("echo Y | sudo apt-get install libcairo2-dev")
system("echo Y | sudo apt-get install -y libxt-dev")
system("echo Y | sudo apt-get install gcc-7 g++-7 gfortran-7")
system("echo Y | sudo apt-get install -y apt-utils")
system("echo Y | sudo apt-get install libxml2-dev")
system("echo Y | sudo apt-get install libgdal-dev")
system("echo Y | sudo apt install libharfbuzz-dev ")
system("echo Y | sudo apt install libfribidi-dev")
system("echo Y | sudo apt install libudunits2-dev")
BiocManager::install("rgdal",force = TRUE)
system("echo Y | sudo apt-get install libglpk-dev ")
BiocManager::install("Cairo")
install.packages("igraph")
# BiocManager::install("FlowSOM")
# BiocManager::install("flowCore")
# BiocManager::install("SummarizedExperiment")
# BiocManager::install("HDCytoData")
# BiocManager::install("CATALYST")
BiocManager::install("scater")
BiocManager::install("pheatmap")
BiocManager::install("plyr")
BiocManager::install("ggplot2")
install.packages("uwot")
install.packages("devtools")
# devtools::install_github("JinmiaoChenLab/Rphenograph")
BiocManager::install("gridExtra")
BiocManager::install("ggpubr")
BiocManager::install("Seurat")
remotes::install_github('chris-mcginnis-ucsf/DoubletFinder')
BiocManager::install("Matrix")
BiocManager::install("biomaRt")
BiocManager::install("DESeq2")
BiocManager::install("plotrix")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("clusterProfiler")
BiocManager::install("DOSE")
BiocManager::install("enrichplot")
BiocManager::install("clusterProfiler")
BiocManager::install("ReactomePA")
BiocManager::install("ggnewscale")
BiocManager::install("AnnotationDbi")
BiocManager::install("schex")
install.packages("lintr")
install.packages("styler")
install.packages("formatR")


install.packages("")

BiocManager::install("")

system("echo Y | ")
